# Hàm Valid_Matrix để thêm cái weight vào với nhau 

In [1]:
import numpy as np 
from numba import njit 
def is_linearly_independent(matrix):
    rank = np.linalg.matrix_rank(matrix)
    return rank == matrix.shape[0]
# Test the function
matrix = np.array([[0.,1.,-1., 0.], [-1.,0., 0.,1.], [1.,0., 0.,1.]])
print(is_linearly_independent(matrix))  # True


True


# Cách rút gọn search space để tìm bộ weight 

# Tạo ra toàn bộ search space cho weight của 1 feature 

In [2]:
size = 161

# generate all possible combinations of indices for the 1 and -1
combinations = [(i, j) for i in range(size) for j in range(size) if i != j]

# create the arrays using the combinations
arrays = []
for (i, j) in combinations:
  arr = [0] * size
  arr[i] = 1
  arr[j] = -1
  arrays.append(arr)

# print the resulting arrays
print(np.array(arrays))


[[ 1 -1  0 ...  0  0  0]
 [ 1  0 -1 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ... -1  0  1]
 [ 0  0  0 ...  0 -1  1]]


In [ ]:
import itertools

def all_submatrices(matrix, num_rows):
    # Get the number of rows and columns in the matrix
    num_cols = len(matrix[0])
    # Iterate over all possible combinations of rows
    for combination in itertools.combinations(range(10), num_rows):
        # Create a new submatrix using the selected rows
        submatrix = [matrix[row] for row in combination]
        yield np.array(submatrix)

# Example usage
all_submatris = []
matrix = arrays
for submatrix in all_submatrices(matrix, 5):
    if is_linearly_independent(submatrix):
        all_submatris.append(submatrix)
        # print(submatrix)
print((all_submatris)[0])
print(len(all_submatris))


In [4]:
%cd /Users/trancatkhanh/Downloads/GAME
from base.Splendor_v3.env import *

high_values_matrix = []
k = 0
for i in range(len(all_submatris)):
    k +=1
    perx = all_submatris[i].astype(np.float64)
    @njit
    def p0(state,per):
        actions = getValidActions(state)
        matran1 = per@state    
        matran1 = 1*(matran1 >= 0)
        if np.sum(matran1) == 5 and 0 in actions :
            action = 0

        return action,per
    win1, x = numba_main_2(p0, 100,perx,0)
    print('process : {}/{}'.format(k, len(all_submatris)), end='\r')
    high_values_matrix.append(i)


/Users/trancatkhanh/Downloads/GAME


In [ ]:
%cd /Users/trancatkhanh/Downloads/GAME
from base.Splendor_v3.env import *

high_values_matrix = []
k = 0
for i in range(len(all_submatris)):
    k +=1
    perx = all_submatris[i].astype(np.float64)
    @njit
    def p0(state,per):
        actions = getValidActions(state)
        matran1 = per@state    
        matran1 = 1*(matran1 >= 0)
        if np.sum(matran1) == 5 and 0 in actions :
            action = 0

        return action,per
    win1, x = numba_main_2(p0, 100,perx,0)
    print('process : {}/{}'.format(k, len(all_submatris)), end='\r')
    high_values_matrix.append(win1)