# Hàm Valid_Matrix để thêm cái weight vào với nhau 

In [1]:
import numpy as np 
from numba import njit 
def is_linearly_independent(matrix):
    rank = np.linalg.matrix_rank(matrix)
    return rank == matrix.shape[0]
# Test the function
matrix = np.array([[0.,1.,-1., 0.], [-1.,0., 0.,1.], [1.,0., 0.,1.]])
print(is_linearly_independent(matrix))  # True


True


# Cách rút gọn search space để tìm bộ weight 

**Tạo ra toàn bộ search space cho weight của 1 feature**

In [2]:
size = 161

# generate all possible combinations of indices for the 1 and -1
combinations = [(i, j) for i in range(size) for j in range(size) if i != j]

# create the arrays using the combinations
arrays = []
for (i, j) in combinations:
  arr = [0] * size
  arr[i] = 1
  arr[j] = -1
  arrays.append(arr)

# print the resulting arrays
print(np.array(arrays))


[[ 1 -1  0 ...  0  0  0]
 [ 1  0 -1 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ... -1  0  1]
 [ 0  0  0 ...  0 -1  1]]


**Sau khi sử dụng hàm Valid_Matrix**

In [3]:
import itertools

def all_submatrices(matrix, num_rows):
    # Get the number of rows and columns in the matrix
    num_cols = len(matrix[0])
    # Iterate over all possible combinations of rows
    for combination in itertools.combinations(range(10), num_rows):
        # Create a new submatrix using the selected rows
        submatrix = [matrix[row] for row in combination]
        yield np.array(submatrix)

# Example usage
all_submatris = []
matrix = arrays
for submatrix in all_submatrices(matrix, 5):
    if is_linearly_independent(submatrix):
        all_submatris.append(submatrix)
        # print(submatrix)
print((all_submatris)[0])
print(len(all_submatris))


[[ 1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1

**Tính số trận thắng của từng ma trận**

In [5]:
%cd /Users/trancatkhanh/Downloads/GAME
from base.Splendor_v3.env import *
high_values_matrix = []
k = 0
for i in range(len(all_submatris)):
    k +=1
    perx = all_submatris[i].astype(np.float64)
    @njit
    def p0(state,per):
        actions = getValidActions(state)
        matran1 = per@state    
        matran1 = 1*(matran1 >= 0)
        if np.sum(matran1) == 5 and 0 in actions :
            action = 0
        return action,per
    win1, x = numba_main_2(p0, 100,perx,0)
    print('process : {}/{}'.format(k, len(all_submatris)), end='\r')
    high_values_matrix.append(win1)

/Users/trancatkhanh/Downloads/GAME


In [50]:
print(bias_greedy)

[0.95421536 0.9898739  1.         0.99400982 0.90169549 0.92428845
 0.92009381 0.93070293 0.94557831 0.93166746 0.90994471 0.9140088
 0.93179905 0.95041808 0.91198727]


In [52]:
per1 = all_submatris[high_values_matrix.index(max(high_values_matrix))].astype(np.float64)
per1

array([[ 1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,

In [59]:
%cd /Users/trancatkhanh/Downloads

PermissionError: [Errno 1] Operation not permitted

In [53]:
per1 = all_submatris[high_values_matrix.index(max(high_values_matrix))].astype(np.float64)
@njit
def p0(state,per):
    actions = getValidActions(state)
    matran1 = per[0]@state    
    matran1 = 1*(matran1 >= 0)
    actions = np.where(actions == 1)[0]
    if np.sum(matran1) == 5 and 0 in actions :
        action = 0
    else:
        list_action2 = getValidActions(state)
        action = np.argmax(list_action2*bias_greedy)
    return action,per
win1, x = numba_main_2(p0, 10,per1,0)
print('phần trăm trận thắng 10 của action ',win1/10)

PermissionError: [Errno 1] Operation not permitted

In [36]:
matrix.shape
perx = [matrix,np.zeros((12,60))]
for i in range(0,12):
    for j in range(5):
        perx[1][i][i*5+j] = 1

In [39]:
@njit
def p0(state,per):
    actions = getValidActions(state)
    matran1 = per[0]@state
    for i in range(len(matran1)):
        matran1[i] = int(matran1[i] >= 0)    
    matran2 = per[1]@matran1
    matran2 *= actions

    action = np.argmax(matran2)
    return action,per
win1, x = numba_main_2(p0, 100,perx,0)
print(win1)

39
